Repository caicloud/mongo-k8s-sidecar, pull requests merged in 2020-03, with the labels that each got.

#13 feat(*): support arm64 building
  Dockerfile.arm64
Labels: caicloud-cla: yes, lgtm, release-note-none, size/S

#14 feat(armv64): change mongo-k8s-sidecar base images
  Dockerfile.arm64
Labels: caicloud-cla: yes, lgtm, release-note-none, size/XS

#15 feat(*): add localization
  release/infra-mongo-bak.yaml
  release/infra-mongo.yaml
Labels: caicloud-cla: yes, release-note-none, size/XS
